import { useEffect, useState } from "react";
import { api } from "../api";
import type { Advisory } from "../types";

const LANGS: { id: string; label: string }[] = [
  { id: "en", label: "English" },
  { id: "hi", label: "हिन्दी" },
  { id: "mr", label: "मराठी" },
];

export default function AdvisoryModal({ city, hex, onClose }: { city: string; hex: string; onClose: () => void }) {
  const [lang, setLang] = useState("en");
  const [advisory, setAdvisory] = useState<Advisory | null>(null);

  useEffect(() => {
    setAdvisory(null);
    api.advisory(city, hex, lang).then(setAdvisory).catch(() => setAdvisory(null));
  }, [city, hex, lang]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/30 p-4 backdrop-blur-sm" onClick={onClose}>
      <div
        className="w-full max-w-lg rounded-2xl border border-slate-200 bg-white p-6 shadow-2xl shadow-slate-900/10"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="mb-4 flex items-center justify-between">
          <h3 className="text-lg font-semibold tracking-tight text-slate-900">Citizen advisory</h3>
          <button
            onClick={onClose}
            className="rounded-lg p-1 text-slate-400 transition hover:bg-slate-100 hover:text-slate-700"
          >
            ✕
          </button>
        </div>
        <div className="mb-4 inline-flex rounded-xl border border-slate-200 bg-slate-100/70 p-1">
          {LANGS.map((l) => (
            <button
              key={l.id}
              onClick={() => setLang(l.id)}
              className={`rounded-lg px-3.5 py-1 text-sm font-medium transition ${
                lang === l.id ? "bg-white text-sky-700 shadow-sm ring-1 ring-slate-200" : "text-slate-500 hover:text-slate-800"
              }`}
            >
              {l.label}
            </button>
          ))}
        </div>
        <div className="whitespace-pre-wrap rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm leading-relaxed text-slate-700">
          {advisory ? advisory.text : "Loading…"}
        </div>
        {advisory && (
          <p className="mt-2.5 text-xs text-slate-400">Generated by: {advisory.generated_by}</p>
        )}
      </div>
    </div>
  );
}
