import { useEffect, useState } from "react";
import { api } from "../api";
import type { Advisory } from "../types";

const LANGS: { id: string; label: string }[] = [
  { id: "en", label: "English" },
  { id: "hi", label: "हिन्दी" },
  { id: "mr", label: "मराठी" },
];

export default function AdvisoryModal({ city, hex, onClose }: { city: string; hex: string; onClose: () => void }) {
  const [lang, setLang] = useState("en");
  const [advisory, setAdvisory] = useState<Advisory | null>(null);

  useEffect(() => {
    setAdvisory(null);
    api.advisory(city, hex, lang).then(setAdvisory).catch(() => setAdvisory(null));
  }, [city, hex, lang]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" onClick={onClose}>
      <div
        className="w-full max-w-lg rounded-xl border border-slate-700 bg-slate-900 p-5"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="mb-3 flex items-center justify-between">
          <h3 className="text-lg font-semibold text-slate-100">Citizen advisory</h3>
          <button onClick={onClose} className="text-slate-400 hover:text-white">✕</button>
        </div>
        <div className="mb-3 inline-flex rounded-lg border border-slate-800 p-1">
          {LANGS.map((l) => (
            <button
              key={l.id}
              onClick={() => setLang(l.id)}
              className={`rounded-md px-3 py-1 text-sm ${
                lang === l.id ? "bg-sky-600 text-white" : "text-slate-300"
              }`}
            >
              {l.label}
            </button>
          ))}
        </div>
        <div className="whitespace-pre-wrap rounded-lg bg-slate-950 p-4 text-sm leading-relaxed text-slate-200">
          {advisory ? advisory.text : "Loading…"}
        </div>
        {advisory && (
          <p className="mt-2 text-xs text-slate-500">Generated by: {advisory.generated_by}</p>
        )}
      </div>
    </div>
  );
}
